<?php
require_once('../TCPDF-main/tcpdf.php'); // Adjust the path as needed
include("db_connection.php");

// Create new PDF document
$pdf = new TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);

// Set document information
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor('DIT Classroom Reservation System');
$pdf->SetTitle('Comments and Recommendations Report');
$pdf->SetSubject('PDF Report');
$pdf->SetKeywords('TCPDF, PDF, report, comments, recommendations');

// Set default header data
$pdf->SetHeaderData('', 0, 'DAR ES SALAAM INSTITUTE OF TECHNOLOGY', 'Generated by DIT Classroom Reservation System');

// Set header and footer fonts
$pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
$pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));

// Set default monospaced font
$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

// Set margins
$pdf->SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_TOP, PDF_MARGIN_RIGHT);
$pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);

// Set auto page breaks
$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);

// Set image scale factor
$pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);

// Add a page
$pdf->AddPage();

// Set content
$html = '<h1>Comments and Recommendations Report</h1>';
$html .= '<table border="1" cellpadding="5">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Comment</th>
                    <th>Recommendation</th>
                </tr>
            </thead>
            <tbody>';

$sql = "SELECT users.firstname, comments.comment_description, comments.recommendation 
        FROM comments 
        INNER JOIN users ON comments.user_id = users.id";
$result = $conn->query($sql);
if ($result->num_rows > 0) {
    while ($row = $result->fetch_assoc()) {
        $html .= '<tr>';
        $html .= '<td>' . htmlspecialchars($row['firstname']) . '</td>';
        $html .= '<td>' . htmlspecialchars($row['comment_description']) . '</td>';
        $html .= '<td>' . htmlspecialchars($row['recommendation']) . '</td>';
        $html .= '</tr>';
    }
} else {
    $html .= '<tr><td colspan="3">No comments and recommendations found.</td></tr>';
}

$html .= '</tbody></table>';

// Print text using writeHTMLCell()
$pdf->writeHTML($html, true, false, true, false, '');

// Close and output PDF document
$pdf->Output('comments_and_recommendations_report.pdf', 'I');
?>
